### ISSUE TITLE
Training a model without validatation.

### ISSUE THREAD

**Issue by yevgenm** [kamperh/globalphone_awe#1]
I was trying to train some models without validation, and AE-RNN training goes well. But CAE-RNN breaks immediately.

The code in train_cae_rnn.py calls train_fixed_epochs:
https://github.com/kamperh/globalphone_awe/blob/a23dcbb98d17df0c74cca6c57e632c2e09394cb2/embeddings/train_cae_rnn.py#L490-L495

This call to train_fixed_epochs does not provide validation_feed_iterator, which is required in line 108 of training.py:
https://github.com/kamperh/globalphone_awe/blob/a23dcbb98d17df0c74cca6c57e632c2e09394cb2/src/training.py#L104-L112

Is there something I'm doing wrong?

**Comment by kamperh** [comment]
I think there was a mistake in these lines:
https://github.com/kamperh/globalphone_awe/blob/a23dcbb98d17df0c74cca6c57e632c2e09394cb2/embeddings/train_cae_rnn.py#L490-L495

It should have been:
```
                cae_record_dict = training.train_fixed_epochs(
                    options_dict["cae_n_epochs"], optimizer, loss,
                    train_batch_iterator, [a, a_lengths, b, b_lengths],
                    save_model_fn=intermediate_model_fn, 
                    load_model_fn=cae_pretrain_model_fn
                    )
```
I've pushed this fix.  Let me know if it works and I'll close the issue.

**Comment by yevgenm** [comment]
That solved it, thanks a lot!
