### ISSUE TITLE
Number of batches

### ISSUE THREAD

**Issue by yevgenm** [kamperh/globalphone_awe#2]
I think there is a small bug with batching of test files. This line:
https://github.com/kamperh/globalphone_awe/blob/77c449abb8c525caacfd9577d4d7b2251c66443c/embeddings/batching.py#L32
Should probably read as follows (or something similar), to round the number of batches up:
`self.n_batches = int(np.ceil(float(len(self.x_lengths))/batch_size))`

**Comment by kamperh** [comment]
I think you are right!  If you confirm that that change works, I'll just work that in.

**Comment by yevgenm** [comment]
Confirmed!
